language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

services:
  - mysql

before_install:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS `untraceables_test`;'
  - mysql -uroot -e "CREATE USER 'untraceables'@'localhost' IDENTIFIED BY 'mmRXHqnc3zSshYjxSv8n';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON untraceables_test . * TO 'untraceables'@'localhost';"
  - mysql -uroot -D untraceables_test -e 'CREATE TABLE `users` (`id` int(10) unsigned NOT NULL, `mapped_id` int(10) unsigned NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `mapped_id` (`mapped_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;';
  - mysql -uroot -D untraceables_test -e 'INSERT INTO `users` (`id`, `mapped_id`) VALUES (0, 10), (1, 9), (2, 8);';

install: make init-dev

before_script:
  - export PYTHONPATH="${PYTHONPATH}:$(pwd)"

script:
  - make check
  - make test
  - make source
  - pip install --upgrade dist/untraceables-*.tar.gz

notifications:
  email: false
  slack:
    rooms:
      secure: "4/IX3mVZcuDbPszD3zRgcu3FLWQafgaWdj7jZ+J9xdt94j0rtlanw3cCifed8+RXtarIGQUk1mUt6UXF9wdG3lgaS3zCLAXJfkyBs/i8gKOUQRWpDATpFCkPGOyz2FcYKLAdefkMQz8SmrJ5aLVb20jqxYAsgs8SNsrf3z7LrAeOY8tCPgBVXSQjIGfU8TckEObDLuIdZcPrVgGRoHcT2kBMQk4dlcosChlItv7pi/dB6svJM89Nrv1QRd644NNRwslQ2+jw2CPitbHbRrEWjp0NRg18e9io0P7iMOnrRjuWPhY6+3Nzxv7/q9IO2rK4zXxGK4rlJNMC/61qYb1Khak0eeLhUaatsQaIpPTXG30SEYvIyZpNJQGpawN3dyBTQW17D4kBni/N9ruXs+rhYve/k7WS2I1BjrDellHmIJ4PT/Y5pOAx5HE00w1f00K3LZLaBizhU/R7WzRgbhQjqO2RyItZZGG0fX0lcyUVRP5RPFJAPDX5M8vYyfT/HWLB80q1PSY8Zt+x0vVOtkzqmQkfBnr1hx9XYlT9zbkBs1tw8UxsDYQC2f+aXFKtq0EHBDijCWy05VEGIR+WwID9MHBLrd+EYec713DVrk7TFwI34t3izfhSaU0novOdZqpliqKepBnF92FNKRj5nQ1UEKjDgqat2bm26MhR43+tnH0="
